### ISSUE TITLE
Move left of the clock

### ISSUE THREAD

**Issue by jhasse** [phocean/TopIcons-plus#2]
I'm using [Frippery Move Clock](https://extensions.gnome.org/extension/2/move-clock/) together with this extension. The TrayIcons are right of the clock, which is kind of confusing. Is there a way to move it left to it? Or should this be changed in the Frippery Move Clock extension?

**Comment by phocean** [comment]
It is up to the TopIcons extension to support it or not. I am trying to implement a new option for that.

**Comment by phocean** [comment]
Please test it and let me know if it works fine on your machine :-)

**Comment by jhasse** [comment]
Thanks for the fast fix! It works fine, but it was not exactly what I had in mind. I thought of having the icons still right-aligned but the clock (also right-aligned) is "more right". So basically swapping the (frippery moved) clock and the icons. Sorry, if it's hard to understand what I mean ;)

**Comment by phocean** [comment]
Oh, understood now. I can also add a setting for that, a weight to move it around between other objects.

**Comment by jhasse** [comment]
Thanks! You should really put this extension up on GNOME Extensions, it's awesome :)

**Comment by phocean** [comment]
Thank you for the feedback and for the ideas :-)
I did submit it but so far nobody has reviewed / validated it there. I will probably take some time.

**Comment by phocean** [comment]
Done but with some unsatisfying hacks regarding the tray position. I found no helpful documentation to fix it. Any help or suggestion is welcome !

**Comment by jhasse** [comment]
I think you did it correct, other extensions don't implement it any different.

With the new update, the mouseover isn't working though. Is that normal?

**Comment by phocean** [comment]
I was not aware of this one, it should be fixed now... ;-)

**Comment by jhasse** [comment]
Thanks!

I think you forgot to uncomment these three lines: https://github.com/phocean/TopIcons/blob/master/extension.js#L224

**Comment by phocean** [comment]
Yes, thanks, already fixed meanwhile. I need a rest away from this extension!
